apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: nadavops/dynamic_domain_page@sha256:f3349835e6cda390dde8e2b92d4f9722b71c4cd1ccbfaaa52d30f800ea58e05f
        ports:
        - containerPort: 80
