apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}
spec:
  ingressClassName: "{{ .Release.Namespace }}-ingress-nginx"
  rules:
  - host: "{{ .Chart.Name }}-{{ .Release.Name }}.{{ .Values.domain_name }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Chart.Name }}-{{ .Release.Name }}
            port:
              number: 80
