apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}-{{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
